In [ ]:
import numpy as np
import math

MAX = 100

def gaussian_elimination(A, B):
    # ... (your existing Gaussian Elimination code)
    n = len(A)

    augmented_matrix = []
    for i in range(n):
        augmented_matrix.append(A[i] + [B[i][0]])

    for i in range(n):
        max_row = i
        for j in range(i + 1, n):
            if abs(augmented_matrix[j][i]) > abs(augmented_matrix[max_row][i]):
                max_row = j
        augmented_matrix[i], augmented_matrix[max_row] = augmented_matrix[max_row], augmented_matrix[i]

        for j in range(i + 1, n):
            factor = augmented_matrix[j][i] / augmented_matrix[i][i]
            for k in range(i, n + 1):
                augmented_matrix[j][k] -= factor * augmented_matrix[i][k]

    X = [0] * n
    for i in range(n - 1, -1, -1):
        X[i] = augmented_matrix[i][-1]
        for j in range(i + 1, n):
            X[i] -= augmented_matrix[i][j] * X[j]
        X[i] /= augmented_matrix[i][i]

    return X

def gauss_jordan_elimination(A, B):
    # ... (your existing Gauss Jordan Elimination code)
    n = len(A)

    for i in range(n):
        # Check if the diagonal element is zero, if so, swap rows
        if A[i][i] == 0:
            for k in range(i + 1, n):
                if A[k][i] != 0:
                    A[i], A[k] = A[k], A[i]
                    B[i], B[k] = B[k], B[i]
                    break
            else:
                return None  # Matrix is singular, no unique solution

        pivot = A[i][i]

        # Normalize the pivot row
        for j in range(n):
            A[i][j] /= pivot
        for j in range(len(B[i])):
            B[i][j] /= pivot

        # Eliminate other rows
        for k in range(n):
            if k != i:
                factor = A[k][i]
                for j in range(n):
                    A[k][j] -= factor * A[i][j]
                for j in range(len(B[k])):
                    B[k][j] -= factor * B[i][j]
    return B
def lu_decomposition(mat, n):
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]

    # Decomposing matrix into Upper
    # and Lower triangular matrix
    for i in range(n):
        # Upper Triangular
        for k in range(i, n):
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
            # Evaluating U(i, k)
            upper[i][k] = mat[i][k] - sum

        # Lower Triangular
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal as 1
            else:
                # Summation of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
                # Evaluating L(k, i)
                lower[k][i] = int((mat[k][i] - sum) /
                                 upper[i][i])

    # Displaying the result
    print("Lower Triangular\t\tUpper Triangular")
    for i in range(n):
        # Lower
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
        # Upper
        for j in range(n):
            print(upper[i][j], end="\t")
        print("")

def cholesky_decomposition(matrix, n):
    lower = [[0 for x in range(n + 1)]
             for y in range(n + 1)]

    for i in range(n):
        for j in range(i + 1):
            sum1 = 0
            if j == i:
                for k in range(j):
                    sum1 += pow(lower[j][k], 2)
                lower[j][j] = math.sqrt(matrix[j][j] - sum1)
            else:
                for k in range(j):
                    sum1 += (lower[i][k] * lower[j][k])
                if lower[j][j] > 0:
                    lower[i][j] = (matrix[i][j] - sum1) / lower[j][j]

    # Displaying the result
    print("Lower Triangular\t\tTranspose")
    for i in range(n):
        for j in range(n):
            print(lower[i][j], end="\t")
        print("", end="\t")
        for j in range(n):
            print(lower[j][i], end="\t")
        print("")
def crout_decomposition(A):
    # ... (your existing Crout Decomposition code)
    L = np.zeros((3, 3))
    U = np.zeros((3, 3))

    for k in range(0, 3):
        U[k, k] = 1

        for j in range(k, 3):
            sum0 = sum(L[k, s] * U[s, j] for s in range(1, k-1))
            L[k, j] = A[k, j] - sum0

        for j in range(k, 3):
            sum1 = sum(L[k, s] * U[s, j] for s in range(1, k-1))
            U[k, j] = (A[k, j] - sum1) / L[k, k]

    print(" L =", '\n', L, '\n', " U =", '\n', U)
    return L, U

while True:
    print("Linear Algebra Methods Menu:")
    print("1. Gaussian Elimination")
    print("2. Gauss Elimination with Pivoting")
    print("3. LU Decomposition")
    print("4. Cholesky Decomposition")
    print("5. Crout Decomposition")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
        n = int(input("Enter the number of equations: "))
        A = []
        B = []
        for i in range(n):
            row = list(map(float, input(f"Enter coefficients for equation {i+1} (separated by spaces): ").split()))
            A.append(row)
            b = float(input(f"Enter the constant term for equation {i+1}: "))
            B.append([b])
        result = gaussian_elimination(A, B)
        print("Solution X:")
        for i, x in enumerate(result):
            print(f"X{i + 1} =", x)

    elif choice == '2':
        n = int(input("Enter the number of equations: "))
        A = []
        B = []
        for i in range(n):
            row = list(map(float, input(f"Enter coefficients for equation {i+1} (separated by spaces): ").split()))
            A.append(row)
            b = float(input(f"Enter the constant term for equation {i+1}: "))
            B.append([b])
        result = gauss_jordan_elimination(A, B)
        if result is None:
            print("The matrix is singular. No unique solution exists.")
        else:
            print("Solution X:")
            for i, x in enumerate(result):
                print(f"X{i + 1} =", x)

    elif choice == '3':
        n = int(input("Enter the size of the matrix: "))
        mat = []
        for i in range(n):
            row = list(map(float, input(f"Enter row {i+1} (separated by spaces): ").split()))
            mat.append(row)
        lu_decomposition(mat, n)

    elif choice == '4':
        n = int(input("Enter the size of the matrix: "))
        matrix = []
        for i in range(n):
            row = list(map(float, input(f"Enter row {i+1} (separated by spaces): ").split()))
            matrix.append(row)
            if len(matrix[i]) != n:
                print("Error: Input matrix must be square.")
                break
        else:
            cholesky_decomposition(matrix, n)

    elif choice == '5':
        n = int(input("Enter the size of the matrix: "))
        A = []
        for i in range(n):
            row = list(map(float, input(f"Enter row {i+1} (separated by spaces): ").split()))
            A.append(row)
        crout_decomposition(np.array(A))

    elif choice == '6':
        print("Exiting the program.")
        break

    else:
        print("Invalid choice. Please select a valid option.")



Linear Algebra Methods Menu:
1. Gaussian Elimination
2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 1
Enter the number of equations: 3
Enter coefficients for equation 1 (separated by spaces): 1 1 -1
Enter the constant term for equation 1: 7
Enter coefficients for equation 2 (separated by spaces): 1 -1 2
Enter the constant term for equation 2: 3
Enter coefficients for equation 3 (separated by spaces): 2 1 1
Enter the constant term for equation 3: 9
Solution X:
X1 = 6.0
X2 = -1.0
X3 = -2.0
Linear Algebra Methods Menu:
1. Gaussian Elimination
2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 2
Enter the number of equations: 3

Enter coefficients for equation 1 (separated by spaces): 1 1 -1
Enter the constant term for equation 1: 7
Enter coefficients for equation 2 (separated by spaces): 1 -1 2
Enter the constant term for equation 2: 3
Enter coefficients for equation 3 (separated by spaces): 2 1 1
Enter the constant term for equation 3: 9
Solution X:
X1 = [6.0]
X2 = [-1.0]
X3 = [-2.0]
Linear Algebra Methods Menu:
1. Gaussian Elimination
2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 3
Enter the size of the matrix: 3
Enter row 1 (separated by spaces): 1 1 1
Enter row 2 (separated by spaces): 4 3 -1
Enter row 3 (separated by spaces): 3 5 3
Lower Triangular Upper Triangular
1 0 0 1.0 1.0 1.0
4 1 0 0 -1.0 -5.0
3 -2 1 0 0 -10.0
Linear Algebra Methods Menu:
1. Gaussian Elimination
2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 4
Enter the size of the matrix: 3
Enter row 1 (separated by spaces): 4 12 -16
Enter row 2 (separated by spaces): 12 37 -43
Enter row 3 (separated by spaces): -16 -43 98
Lower Triangular Transpose
2.0 0 0 2.0 6.0 -8.0
6.0 1.0 0 0 1.0 5.0
-8.0 5.0 3.0 0 0 3.0
Linear Algebra Methods Menu:
1. Gaussian Elimination

2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 5
Enter the size of the matrix: 3
Enter row 1 (separated by spaces): 2 1 4 12
Enter row 2 (separated by spaces): 8 -3 2 20
Enter row 3 (separated by spaces): 4 11 -1 33
L = [[ 2. 1. 4.]
[ 0. -3. 2.]
[ 0. 0. -1.]]
U = [[ 1. 0.5 2. ]
[ 0. 1. -0.66666667]
[ 0. 0. 1. ]]
Linear Algebra Methods Menu:
1. Gaussian Elimination
2. Gauss Elimination with Pivoting
3. LU Decomposition
4. Cholesky Decomposition
5. Crout Decomposition
6. Exit
Enter your choice: 6
Exiting the program.